---
- name: Install perl-FCGI
  package: name=perl-FCGI state=installed

- name: fastcgi-wrapper
  template:
    src: fastcgi-wrapper.pl.j2
    dest: "{{ fastcgi_wrapper_script }}"
    mode: '0755'

- name: fcgi-perl.service
  template:
    src: fastcgi-service.j2
    dest: /usr/lib/systemd/system/fcgi-perl.service
  notify: fcgi reload

- name: enable fcgi-perl.service
  systemd: name=fcgi-perl enabled=yes state=started
